name: Release
on: 
  workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Release
      uses: qcastel/github-actions-maven-release@master
      with:
        release-branch-name: "master"
        maven-args: "-P sonatype"
        git-release-bot-name: "release-bot"
        git-release-bot-email: "release-bot@fleetpin.co.nz"
        
        gpg-enabled: "true"
        gpg-key-id: ${{ secrets.GPG_KEY_ID }}
        gpg-key: ${{ secrets.GPG_KEY }}
        
        maven-repo-server-id: sonatype
        maven-repo-server-username: ${{ secrets.MVN_REPO_PRIVATE_REPO_USER }}
        maven-repo-server-password: ${{ secrets.MVN_REPO_PRIVATE_REPO_PASSWORD }}
        
        access-token: ${{ secrets.GITHUB_TOKEN }}
